FROM postgis/postgis:16-3.4

# Instalar Python y dependencias como root durante la build
RUN apt-get update -qq && \
    apt-get install -y -qq \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Instalar psycopg2
RUN pip install -q psycopg2-binary
