"""create_initial_map_schema

Revision ID: bc51307a5d47
Revises:
Create Date: 2026-05-22 16:12:50.891335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "bc51307a5d47"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "container_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("volume_m3", sa.DOUBLE_PRECISION(), nullable=True),
        sa.Column("overflow_zone_cm", sa.Integer(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "waste_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "container_type_waste_types",
        sa.Column("container_type_id", sa.BigInteger(), nullable=False),
        sa.Column("waste_type_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_type_id"],
            ["container_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["waste_type_id"],
            ["waste_types.id"],
        ),
        sa.PrimaryKeyConstraint("container_type_id", "waste_type_id"),
    )
    op.create_table(
        "containers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column("serie_id", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("longitude", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("current_level", sa.Integer(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("last_pickup", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_reading", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("site_name", sa.String(), nullable=True),
        sa.Column("device_imei", sa.String(), nullable=True),
        sa.Column("container_type_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["container_type_id"],
            ["container_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id"),
    )
    op.create_index(
        "idx_containers_geom",
        "containers",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_containers_geom", table_name="containers", postgresql_using="gist"
    )
    op.drop_table("containers")
    op.drop_table("container_type_waste_types")
    op.drop_table("waste_types")
    op.drop_table("container_types")
    # ### end Alembic commands ###
