FROM postgis/postgis:16-3.4

# Instalar gdal-bin que contiene la herramienta ogr2ogr necesaria para la importación
RUN apt-get update && \
    apt-get install -y --no-install-recommends gdal-bin && \
    rm -rf /var/lib/apt/lists/*
